export { default as Management } from './Management'
export { default as Login } from './Login'
export { default as Chart } from './Chart'
export { default as Account } from './Account'
export { default as SignUp } from './SignUp'
